version: '3.4'

services:
  guessdb:
    image: mongo

  rabbitmq:
    image: rabbitmq:3-management-alpine

  casenumbersworker:
    image: ${DOCKER_REGISTRY-}casenumbersworker
    build:
      context: .
      dockerfile: Background Processes/CaseNumbersWorker/Dockerfile

  guess.api:
    image: ${DOCKER_REGISTRY-}guess
    build:
      context: .
      dockerfile: Services/Guess/Guess.API/Dockerfile

volumes:
  mongo_data:

