version: '3.4'

services:
  casenumbersworker:
    container_name: casenumbersworker
    restart: always
    environment:
      - DOTNET_ENVIRONMENT=Development
      - "EventBusSettings:HostAddress=amqp://guest:guest@rabbitmq:5672"
    depends_on:
      - rabbitmq

  rabbitmq:
    container_name: rabbitmq
    environment:
      - SA_PASSWORD=SwN12345678
      - ACCEPT_EULA=Y
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672"